// Persists reports generated by POST /api/reports/[name] (see lib/agent-response.ts), so a
// report can eventually be re-read instead of only ever streamed once and discarded.
//
// This is the fix for the Brief-vs-Report duplicate: `Brief`/`BriefItem` (lib/types.ts,
// served by lib/data.ts + mocks/fixtures.ts) is a hand-written stand-in for exactly what a
// real "morning-brief" report row here would be. It stays a stand-in for now — detector
// output (severity, causal chains, dollar impact) needs the future detector/mcp-write-path
// service data/simulator's schema.py already reserves `briefings` for, which this is not.
// This module only makes the *agent's actual report replies* durable and re-readable; wiring
// `/reports` to read real reports instead of fixtures is future work once that reply shape is
// as rich as `Brief`'s.
//
// Reports are per-tenant business data (ARCHITECTURE.md §3.2), so each tenant's rows live in
// its own Postgres schema next to data/simulator's dim_*/fact_* tables — not in `shared`.
// `web` has so far only ever queried the `shared` schema (control-plane tenant lookups); this
// is its first tenant-schema table, and it owns the table because it's the service that
// produces the row. Table names are schema-qualified by interpolating the tenant id directly
// (`"<tenant>".reports`) rather than `SET search_path` on a pooled connection, so a reused
// connection can never leak one tenant's search_path into another request.

import { getPool } from "@/lib/db";
import type { ContentBlock, FileRef, Report, ReportKind, ReportSummary } from "@/lib/types";

// Same shape provision.py enforces for tenant_id (it's used as a Postgres schema/identifier).
const VALID_SCHEMA = /^[a-z][a-z0-9_]{0,62}$/;

function assertValidSchema(tenantId: string): void {
  if (!VALID_SCHEMA.test(tenantId)) throw new Error(`invalid tenant schema name: ${tenantId}`);
}

const ensured = new Set<string>();

async function ensureTable(tenantId: string): Promise<void> {
  if (ensured.has(tenantId)) return;
  assertValidSchema(tenantId);
  const t = `"${tenantId}".reports`;
  await getPool().query(`
    CREATE TABLE IF NOT EXISTS ${t} (
      id text PRIMARY KEY,
      kind text NOT NULL,
      title text NOT NULL,
      session_id text NOT NULL,
      generated_at timestamptz NOT NULL,
      period_start timestamptz NOT NULL,
      period_end timestamptz NOT NULL,
      partial boolean NOT NULL,
      headline text,
      blocks jsonb NOT NULL,
      files jsonb NOT NULL DEFAULT '[]'
    )
  `);
  await getPool().query(`CREATE INDEX IF NOT EXISTS reports_generated_at_idx ON ${t} (generated_at DESC)`);
  ensured.add(tenantId);
}

export type NewReport = {
  kind: ReportKind;
  title: string;
  sessionId: string;
  generatedAt: Date;
  periodStart: Date;
  periodEnd: Date;
  partial: boolean;
  blocks: ContentBlock[];
  file?: FileRef;
};

/** First line of the reply's markdown, if any — good enough for a list view's one-liner. */
function headlineOf(blocks: ContentBlock[]): string | undefined {
  const first = blocks.find((b) => b.type === "markdown");
  const line = first?.type === "markdown" ? first.text.trim().split("\n")[0] : undefined;
  return line?.replace(/^#+\s*/, "") || undefined;
}

export async function saveReport(tenantId: string, report: NewReport): Promise<string> {
  await ensureTable(tenantId);
  const id = crypto.randomUUID();
  const files: FileRef[] = report.file ? [report.file] : [];
  await getPool().query(
    `INSERT INTO "${tenantId}".reports
       (id, kind, title, session_id, generated_at, period_start, period_end, partial, headline, blocks, files)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
    [
      id,
      report.kind,
      report.title,
      report.sessionId,
      report.generatedAt.toISOString(),
      report.periodStart.toISOString(),
      report.periodEnd.toISOString(),
      report.partial,
      headlineOf(report.blocks) ?? null,
      JSON.stringify(report.blocks),
      JSON.stringify(files),
    ],
  );
  return id;
}

type ReportRow = {
  id: string;
  kind: ReportKind;
  title: string;
  generated_at: Date;
  period_start: Date;
  period_end: Date;
  partial: boolean;
  headline: string | null;
  blocks: ContentBlock[];
  files: FileRef[];
};

function toSummary(row: ReportRow): ReportSummary {
  return {
    id: row.id,
    kind: row.kind,
    title: row.title,
    generatedAt: row.generated_at.toISOString(),
    periodStart: row.period_start.toISOString(),
    periodEnd: row.period_end.toISOString(),
    partial: row.partial,
    headline: row.headline ?? undefined,
    files: row.files,
  };
}

/** Newest first — for a future `/reports` or `GET /api/reports` reading real reports. */
export async function listReports(tenantId: string, limit = 50): Promise<ReportSummary[]> {
  assertValidSchema(tenantId);
  const exists = await getPool().query(
    `SELECT 1 FROM information_schema.tables WHERE table_schema = $1 AND table_name = 'reports'`,
    [tenantId],
  );
  if (exists.rows.length === 0) return []; // no report has ever been generated for this tenant yet
  const { rows } = await getPool().query<ReportRow>(
    `SELECT * FROM "${tenantId}".reports ORDER BY generated_at DESC LIMIT $1`,
    [limit],
  );
  return rows.map(toSummary);
}

export async function getReport(tenantId: string, id: string): Promise<Report | null> {
  assertValidSchema(tenantId);
  const exists = await getPool().query(
    `SELECT 1 FROM information_schema.tables WHERE table_schema = $1 AND table_name = 'reports'`,
    [tenantId],
  );
  if (exists.rows.length === 0) return null;
  const { rows } = await getPool().query<ReportRow>(`SELECT * FROM "${tenantId}".reports WHERE id = $1`, [id]);
  const row = rows[0];
  return row ? { ...toSummary(row), blocks: row.blocks } : null;
}
