// Persists reports generated by POST /api/reports/[name] (see lib/agent-response.ts), so a
// report can eventually be re-read instead of only ever streamed once and discarded.
//
// This is the fix for the Brief-vs-Report duplicate: `Brief`/`BriefItem` (lib/types.ts,
// served by lib/data.ts + mocks/fixtures.ts) is a hand-written stand-in for exactly what a
// real "morning-brief" report row here would be. It stays a stand-in for now — detector
// output (severity, causal chains, dollar impact) needs the future detector/mcp-write-path
// service data/simulator's schema.py already reserves `briefings` for, which this is not.
// This module only makes the *agent's actual report replies* durable and re-readable; wiring
// `/reports` to read real reports instead of fixtures is future work once that reply shape is
// as rich as `Brief`'s.
//
// Reports are per-tenant business data (ARCHITECTURE.md §3.2), so each tenant's rows live in
// its own Postgres schema next to data/simulator's dim_*/fact_* tables — not in `shared`.
// `web` has so far only ever queried the `shared` schema (control-plane tenant lookups); this
// is its first tenant-schema table, and it owns the table because it's the service that
// produces the row. Table names are schema-qualified by interpolating the tenant id directly
// (`"<tenant>".reports`) rather than `SET search_path` on a pooled connection, so a reused
// connection can never leak one tenant's search_path into another request.

import { getPool } from "@/lib/db";
import { parseMarkdownLite, plainText, splitLeadAndBody } from "@/lib/report-export/markdown-lite";
import type { Anomaly, ContentBlock, FileRef, Report, ReportKind, ReportSummary } from "@/lib/types";

// Same shape provision.py enforces for tenant_id (it's used as a Postgres schema/identifier).
const VALID_SCHEMA = /^[a-z][a-z0-9_]{0,62}$/;

function assertValidSchema(tenantId: string): void {
  if (!VALID_SCHEMA.test(tenantId)) throw new Error(`invalid tenant schema name: ${tenantId}`);
}

// Doubles as "this tenant's reports table is known to exist" — populated by ensureTable()
// after a save, or by tableKnownToExist() after its first successful existence probe.
const ensured = new Set<string>();

async function ensureTable(tenantId: string): Promise<void> {
  if (ensured.has(tenantId)) return;
  assertValidSchema(tenantId);
  const t = `"${tenantId}".reports`;
  await getPool().query(`
    CREATE TABLE IF NOT EXISTS ${t} (
      id text PRIMARY KEY,
      kind text NOT NULL,
      title text NOT NULL,
      session_id text NOT NULL,
      generated_at timestamptz NOT NULL,
      period_start timestamptz NOT NULL,
      period_end timestamptz NOT NULL,
      partial boolean NOT NULL,
      headline text,
      blocks jsonb NOT NULL,
      files jsonb NOT NULL DEFAULT '[]'
    )
  `);
  // Added after the table first shipped, so tables created before it get it here.
  await getPool().query(`ALTER TABLE ${t} ADD COLUMN IF NOT EXISTS anomalies jsonb NOT NULL DEFAULT '[]'`);
  await getPool().query(`CREATE INDEX IF NOT EXISTS reports_generated_at_idx ON ${t} (generated_at DESC)`);
  ensured.add(tenantId);
}

/** listReports/getReport run on every Reports-page navigation and used to each pay for their
 * own `information_schema.tables` round trip, on top of the actual query — a tenant that has
 * ever generated one report was proving the table exists again on every single click. Checking
 * `ensured` first (populated by ensureTable() the first time this tenant saves a report, or by
 * this function's own first successful probe) means that round trip is paid at most once per
 * tenant per server process instead of once per request. */
async function tableKnownToExist(tenantId: string): Promise<boolean> {
  if (ensured.has(tenantId)) return true;
  assertValidSchema(tenantId);
  const { rows } = await getPool().query(
    `SELECT 1 FROM information_schema.tables WHERE table_schema = $1 AND table_name = 'reports'`,
    [tenantId],
  );
  if (rows.length === 0) return false;
  ensured.add(tenantId);
  return true;
}

export type NewReport = {
  kind: ReportKind;
  title: string;
  sessionId: string;
  generatedAt: Date;
  periodStart: Date;
  periodEnd: Date;
  partial: boolean;
  blocks: ContentBlock[];
  files?: FileRef[];
  anomalies?: Anomaly[];
};

/** The reply's own executive-summary sentence, if any — same lead the PDF/Excel exports and
 * the Reports page's detail view (ReportInsights) callout use, so the list row's one-liner
 * never disagrees with what opening the report shows. Falls back to the raw first line for a
 * reply with no real prose (e.g. only a chart/table). */
function headlineOf(blocks: ContentBlock[], title: string): string | undefined {
  const first = blocks.find((b): b is Extract<ContentBlock, { type: "markdown" }> => b.type === "markdown" && b.text.trim() !== "");
  if (!first) return undefined;
  const { lead } = splitLeadAndBody(parseMarkdownLite(first.text), title);
  if (lead?.length) return plainText(lead);
  return first.text.trim().split("\n")[0]?.replace(/^#+\s*/, "") || undefined;
}

export async function saveReport(tenantId: string, report: NewReport): Promise<string> {
  await ensureTable(tenantId);
  const id = crypto.randomUUID();
  const files: FileRef[] = report.files ?? [];
  await getPool().query(
    `INSERT INTO "${tenantId}".reports
       (id, kind, title, session_id, generated_at, period_start, period_end, partial, headline, blocks, files, anomalies)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`,
    [
      id,
      report.kind,
      report.title,
      report.sessionId,
      report.generatedAt.toISOString(),
      report.periodStart.toISOString(),
      report.periodEnd.toISOString(),
      report.partial,
      headlineOf(report.blocks, report.title) ?? null,
      JSON.stringify(report.blocks),
      JSON.stringify(files),
      JSON.stringify(report.anomalies ?? []),
    ],
  );
  return id;
}

type ReportListRow = {
  id: string;
  kind: ReportKind;
  title: string;
  generated_at: Date;
  period_start: Date;
  period_end: Date;
  partial: boolean;
  headline: string | null;
};
type ReportRow = ReportListRow & { blocks: ContentBlock[]; files: FileRef[]; anomalies?: Anomaly[] };

function toSummary(row: ReportListRow & { anomalies?: Anomaly[] }): ReportSummary {
  return {
    id: row.id,
    kind: row.kind,
    title: row.title,
    generatedAt: row.generated_at.toISOString(),
    periodStart: row.period_start.toISOString(),
    periodEnd: row.period_end.toISOString(),
    partial: row.partial,
    headline: row.headline ?? undefined,
    // Nothing in the UI reads a list row's `files` today (see ReportSummary's doc comment) —
    // each row's real value is a base64-encoded PDF + Excel, easily tens of KB, so fetching it
    // for every row on every list navigation would multiply that cost for no benefit. A future
    // list UI that wants download links here should query for them explicitly.
    files: [],
    // Missing on a table ensureTable hasn't migrated yet (nothing saved since the column landed).
    anomalies: row.anomalies ?? [],
  };
}

/** Newest first — for a future `/reports` or `GET /api/reports` reading real reports. Selects
 * only the list's own columns (not `blocks`/`files`, the two heavy jsonb columns) — the list
 * never renders either, and pulling them for every row on every navigation was the single
 * biggest cost on this page. */
export async function listReports(tenantId: string, limit = 50): Promise<ReportSummary[]> {
  assertValidSchema(tenantId);
  if (!(await tableKnownToExist(tenantId))) return []; // no report has ever been generated for this tenant yet
  const { rows } = await getPool().query<ReportListRow & { anomalies?: Anomaly[] }>(
    `SELECT id, kind, title, generated_at, period_start, period_end, partial, headline, anomalies
       FROM "${tenantId}".reports ORDER BY generated_at DESC LIMIT $1`,
    [limit],
  );
  return rows.map(toSummary);
}

export async function getReport(tenantId: string, id: string): Promise<Report | null> {
  assertValidSchema(tenantId);
  if (!(await tableKnownToExist(tenantId))) return null;
  const { rows } = await getPool().query<ReportRow>(`SELECT * FROM "${tenantId}".reports WHERE id = $1`, [id]);
  const row = rows[0];
  return row ? { ...toSummary(row), files: row.files, blocks: row.blocks } : null;
}

/** Deletes one report. False if there was no such report. */
export async function deleteReport(tenantId: string, id: string): Promise<boolean> {
  assertValidSchema(tenantId);
  if (!(await tableKnownToExist(tenantId))) return false;
  const { rowCount } = await getPool().query(`DELETE FROM "${tenantId}".reports WHERE id = $1`, [id]);
  return (rowCount ?? 0) > 0;
}

/** Whether a `kind` report covering the window starting at `periodStart` is already saved — how
 * the scheduler avoids running the same slot twice (restarts, several replicas). */
export async function hasReportFor(tenantId: string, kind: ReportKind, periodStart: Date): Promise<boolean> {
  assertValidSchema(tenantId);
  if (!(await tableKnownToExist(tenantId))) return false;
  const { rows } = await getPool().query(
    `SELECT 1 FROM "${tenantId}".reports WHERE kind = $1 AND period_start = $2 LIMIT 1`,
    [kind, periodStart.toISOString()],
  );
  return rows.length > 0;
}
