"""Canned rows shaped like the eventual warehouse `signals` table."""

DEMO_SIGNALS: list[dict] = [
    {
        "signal_id": "sig-001",
        "detected_at": "2026-09-15T06:00:00Z",
        "metric_id": "revenue.daily",
        "grain": "channel",
        "dimensions": {"channel": "shopee"},
        "period": "2026-09-14",
        "observed": 18250.0,
        "expected": 26400.0,
        "deviation": -0.309,
        "score": 0.92,
        "dollar_impact_est": -8150.0,
        "detector": "seasonal_zscore",
        "status": "open",
    },
    {
        "signal_id": "sig-002",
        "detected_at": "2026-09-15T06:00:00Z",
        "metric_id": "stock.days_of_cover",
        "grain": "sku",
        "dimensions": {"sku": "TEE-BLK-M"},
        "period": "2026-09-14",
        "observed": 2.0,
        "expected": 14.0,
        "deviation": -0.857,
        "score": 0.81,
        "dollar_impact_est": -3200.0,
        "detector": "threshold",
        "status": "open",
    },
    {
        "signal_id": "sig-003",
        "detected_at": "2026-09-14T06:00:00Z",
        "metric_id": "supplier.lead_days",
        "grain": "supplier",
        "dimensions": {"supplier": "Northwind Textiles"},
        "period": "2026-W37",
        "observed": 19.0,
        "expected": 12.0,
        "deviation": 0.583,
        "score": 0.64,
        "dollar_impact_est": -1100.0,
        "detector": "rolling_median",
        "status": "acknowledged",
    },
]
